//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public Nullable<int> hospital_id { get; set; }
        public Nullable<int> vaccine_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> reason_id { get; set; }
        public Nullable<int> step { get; set; }
        public Nullable<int> approve { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<System.DateTime> date_2 { get; set; }
    }
}
