//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth_tokens
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string token { get; set; }
        public Nullable<System.DateTime> expired { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
