//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_rows
    {
        public int id { get; set; }
        public int data_type_id { get; set; }
        public string field { get; set; }
        public string type { get; set; }
        public string display_name { get; set; }
        public bool required { get; set; }
        public bool browse { get; set; }
        public bool read { get; set; }
        public bool edit { get; set; }
        public bool add { get; set; }
        public bool delete { get; set; }
        public string details { get; set; }
        public int order { get; set; }
    
        public virtual data_types data_types { get; set; }
    }
}
