//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_types
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public data_types()
        {
            this.data_rows = new HashSet<data_rows>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public string display_name_singular { get; set; }
        public string display_name_plural { get; set; }
        public string icon { get; set; }
        public string model_name { get; set; }
        public string description { get; set; }
        public bool generate_permissions { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public byte server_side { get; set; }
        public string controller { get; set; }
        public string policy_name { get; set; }
        public string details { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<data_rows> data_rows { get; set; }
    }
}
