//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class hospital
    {
        public int id { get; set; }
        public Nullable<int> province_id { get; set; }
        public string name_kh { get; set; }
        public string name_en { get; set; }
    }
}
