//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class menu_items
    {
        public int id { get; set; }
        public Nullable<int> menu_id { get; set; }
        public string title { get; set; }
        public string url { get; set; }
        public string target { get; set; }
        public string icon_class { get; set; }
        public string color { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int order { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public string route { get; set; }
        public string parameters { get; set; }
    
        public virtual menu menu { get; set; }
    }
}
