//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class position
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> organization_id { get; set; }
        public Nullable<int> priority { get; set; }
        public Nullable<int> status { get; set; }
    }
}
