//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class post
    {
        public int id { get; set; }
        public int author_id { get; set; }
        public Nullable<int> category_id { get; set; }
        public string title { get; set; }
        public string seo_title { get; set; }
        public string excerpt { get; set; }
        public string body { get; set; }
        public string image { get; set; }
        public string slug { get; set; }
        public string meta_description { get; set; }
        public string meta_keywords { get; set; }
        public string status { get; set; }
        public bool featured { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
