//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class translation
    {
        public int id { get; set; }
        public string table_name { get; set; }
        public string column_name { get; set; }
        public int foreign_key { get; set; }
        public string locale { get; set; }
        public string value { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
