//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AndroidContact
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public long id { get; set; }
        public Nullable<long> role_id { get; set; }
        public Nullable<int> province_id { get; set; }
        public Nullable<int> district_id { get; set; }
        public Nullable<int> commune_id { get; set; }
        public Nullable<int> village_id { get; set; }
        public Nullable<int> position_id { get; set; }
        public Nullable<int> organization_id { get; set; }
        public string username { get; set; }
        public string name_kh { get; set; }
        public string name_en { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> email_verified_at { get; set; }
        public string password { get; set; }
        public string qr_code_server { get; set; }
        public string qr_code_ministry { get; set; }
        public string phone { get; set; }
        public string remember_token { get; set; }
        public string avatar { get; set; }
        public string settings { get; set; }
        public string gender { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public string national_id_card { get; set; }
        public Nullable<int> is_illness { get; set; }
        public Nullable<int> is_alergy { get; set; }
        public Nullable<int> parent_id { get; set; }
        public Nullable<int> age { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> attempt_login { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    }
}
